# SPDX-FileCopyrightText: 2025 Alec Delaney
# SPDX-License-Identifier: MIT

name: 'Fork Instead'
description: 'Let others know that they should instead fork your repository and fix issues locally'
author: Alec "tekktrik" Delaney

branding:
  icon: 'git-branch'
  color: 'blue'


inputs:
  github-token:
    description:
      The GitHub token needed to authenticate, must have write permessions
      for issues and/or pull requests (as necessary)
    required: true
  message:
    description:
      The message to write upon closing the issue or pull request
    default:
      Sorry, this repository is working as intended - please fork this repository
      and fix any "issues" locally.
  on-issues:
    description:
      Whether this action will run whenever issues are opened.  Can be either
      "true" or "false" (default is true).
    default: 'true'
  on-pull-requests:
    description:
      Whether this action will run whenever pull requests are opened.  Can
      be either "true" or "false" (default is false).
    default: 'true'
  lock:
    description:
      Whether to lock the conversation after notifying the user.  Can either
      be "true" or "false" (default is true).
    default: 'true'
  close:
    description:
      Whether to automatically close the issue after notifying the user. Can
      either be "true" or "false" (default is true)
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Install uv
      shell: bash
      run: pipx install uv
    - name: Install the required version on python
      shell: bash
      run: uv python install --project ${{ github.action_path }}
    - name: Run the fork suggestion action
      shell: bash
      run: uv run ${{ github.action_path }}/action.py
      env:
        INPUT_GITHUB_TOKEN: ${{ inputs.github-token }}
        INPUT_MESSAGE: ${{ inputs.message }}
        INPUT_ON_ISSUES: ${{ inputs.on-issues }}
        INPUT_ON_PULL_REQUESTS: ${{ inputs.on-pull-requests }}
        INPUT_LOCK: ${{ inputs.lock }}
        INPUT_CLOSE: ${{ inputs.close }}
        ACTION_REPO: ${{ github.repository }}
        ACTION_EVENT_PATH: ${{ github.event_path }}
