# SPDX-FileCopyrightText: 2023 Alec Delaney
# SPDX-License-Identifier: MIT

name: Working as intended

on:
  issues:
    types: [opened, reopened]
  pull_request:
    types: [opened]

jobs:
  ignore:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: FastAndCheap/fork-instead@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          on-issues: true
          on-pull-requests: true
          lock: true
          close: true
